import type { Metadata } from "next";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Main Layout Container */}
        <div className="flex flex-col">

          {/* Top Navigation */}
          <header className="text-white shadow-md">
            <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
              <h1 className="text-2xl font-bold font-[family-name:var(--font-geist-mono)]">Github Explorer</h1>
              <nav>
                <ul className="flex space-x-6">
                  <li><a href="/" className="hover:text-gray-300">Home</a></li>
                </ul>
              </nav>
            </div>
          </header>

          {/* Main Content Area */}
          <ReactQueryProvider>
            <main className="flex-1 p-6">
              {/* Children Content */}
              {children}
            </main>
          </ReactQueryProvider>

        </div>
      </body>
    </html>
  );
}
